// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using discord_clicker.Models;

namespace discord_clicker.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20220206121539_w")]
    partial class w
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("discord_clicker.Models.Perk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("PassiveCoefficient")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Perks");
                });

            modelBuilder.Entity("discord_clicker.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<long>("ClickCoefficient")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Money")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Nickname")
                        .HasColumnType("text");

                    b.Property<decimal>("PassiveCoefficient")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("discord_clicker.Models.UserPerk", b =>
                {
                    b.Property<int>("PerkId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<long>("Count")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.HasKey("PerkId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPerks");
                });

            modelBuilder.Entity("discord_clicker.Models.UserPerk", b =>
                {
                    b.HasOne("discord_clicker.Models.Perk", "Perk")
                        .WithMany("UserPerks")
                        .HasForeignKey("PerkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("discord_clicker.Models.User", "User")
                        .WithMany("UserPerks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perk");

                    b.Navigation("User");
                });

            modelBuilder.Entity("discord_clicker.Models.Perk", b =>
                {
                    b.Navigation("UserPerks");
                });

            modelBuilder.Entity("discord_clicker.Models.User", b =>
                {
                    b.Navigation("UserPerks");
                });
#pragma warning restore 612, 618
        }
    }
}
